# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 10, 211, 171))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("../../Pictures/WhatsApp Pictures/IMG-20230421-WA0012.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.Victory = QtWidgets.QPushButton(self.centralwidget)
        self.Victory.setGeometry(QtCore.QRect(0, 190, 171, 28))
        self.Victory.setObjectName("Victory")
        self.Emmy = QtWidgets.QPushButton(self.centralwidget)
        self.Emmy.setGeometry(QtCore.QRect(172, 190, 151, 28))
        self.Emmy.setObjectName("Emmy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Victory.clicked.connect(self.show_victory)
        self.Emmy.clicked.connect(self.show_emmy)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Victory.setText(_translate("MainWindow", "Victory"))
        self.Emmy.setText(_translate("MainWindow", "Emmy"))

    def show_victory(self):
        self.photo.setPixmap(QtGui.QPixmap("../../Pictures/WhatsApp Pictures/IMG-20230421-WA0012.jpg"))
    def show_emmy(self):
        self.photo.setPixmap(QtGui.QPixmap("../../Pictures/WhatsApp Pictures/IMG-20230516-WA0009.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
